-- 가게
DROP TABLE IF EXISTS SHOP;
CREATE TABLE SHOP(
    ID BIGINT PRIMARY KEY AUTO_INCREMENT,
    NAME VARCHAR(150) NOT NULL,
    MIN_ORDER_PRICE BIGINT NOT NULL,
    START_TIME TIME NOT NULL,
    END_TIME TIME NOT NULL,
    CATEGORY VARCHAR(50),
    LATITUDE DOUBLE,
    LONGITUDE DOUBLE,
    DELIVERY_RADIUS DOUBLE
);

-- 메뉴
DROP TABLE IF EXISTS MENU;
CREATE TABLE MENU(
    ID BIGINT PRIMARY KEY AUTO_INCREMENT,
    SHOP_ID BIGINT NULL,
    NAME VARCHAR(200) NOT NULL,
    DESCRIPTION VARCHAR(500) NOT NULL,
    BASE_PRICE BIGINT NOT NULL,
    STATUS VARCHAR(10) NOT NULL
);

DROP TABLE IF EXISTS MENU_OPTION_GROUP;
CREATE TABLE MENU_OPTION_GROUP(
    MENU_ID BIGINT,
    OPTION_GROUP_ID BIGINT,
    DISPLAY_ORDER INT,
    CONSTRAINT PK_MENU_OPTION_GROUP PRIMARY KEY (MENU_ID, OPTION_GROUP_ID)
);

-- 옵션 그룹
DROP TABLE IF EXISTS OPTION_GROUP;
CREATE TABLE OPTION_GROUP(
    ID BIGINT PRIMARY KEY AUTO_INCREMENT,
    NAME VARCHAR(100) NOT NULL,
    REQUIRED BOOLEAN NOT NULL
);

DROP TABLE IF EXISTS MENU_OPTION;
CREATE TABLE MENU_OPTION(
    ID BIGINT PRIMARY KEY AUTO_INCREMENT,
    OPTION_GROUP_ID BIGINT NOT NULL,
    NAME VARCHAR(100) NOT NULL,
    PRICE BIGINT NOT NULL,
    CONSTRAINT UQ_OPTION_NAME UNIQUE (OPTION_GROUP_ID, NAME)
);

-- 장바구니
DROP TABLE IF EXISTS CART;
CREATE TABLE CART(
    ID BIGINT PRIMARY KEY AUTO_INCREMENT,
    USER_ID BIGINT NOT NULL,
    SHOP_ID BIGINT NULL
);

DROP TABLE IF EXISTS CART_LINE_ITEM;
CREATE TABLE CART_LINE_ITEM(
    ID BIGINT PRIMARY KEY AUTO_INCREMENT,
    CART_ID BIGINT NULL,
    MENU_ID BIGINT NOT NULL,
    MENU_NAME VARCHAR(200) NOT NULL,
    MENU_COUNT INT NOT NULL,
    UNIT_PRICE BIGINT NOT NULL
);

DROP TABLE IF EXISTS CART_OPTION_GROUP;
CREATE TABLE CART_OPTION_GROUP(
    ID BIGINT PRIMARY KEY AUTO_INCREMENT,
    CART_LINE_ITEM_ID BIGINT NULL,
    OPTION_GROUP_ID BIGINT NOT NULL,
    NAME VARCHAR(100) NOT NULL,
    CONSTRAINT U_CART_OPTION_GROUPS UNIQUE (CART_LINE_ITEM_ID, OPTION_GROUP_ID)
);

DROP TABLE IF EXISTS CART_OPTION;
CREATE TABLE CART_OPTION(
    ID BIGINT PRIMARY KEY AUTO_INCREMENT,
    CART_OPTION_GROUP_ID BIGINT NOT NULL,
    OPTION_ID BIGINT NOT NULL,
    NAME VARCHAR(100) NOT NULL,
    PRICE BIGINT NOT NULL,
    CONSTRAINT U_CART_OPTIONS UNIQUE (CART_OPTION_GROUP_ID, OPTION_ID)
);

-- 주문 (스냅샷 JSON 구조)
DROP TABLE IF EXISTS ORDERS;
CREATE TABLE ORDERS(
    ID BIGINT PRIMARY KEY AUTO_INCREMENT,
    USER_ID BIGINT NOT NULL,
    SHOP_ID BIGINT NOT NULL,
    ORDERED_TIME TIMESTAMP NOT NULL,
    TOTAL_PRICE BIGINT NOT NULL,
    ITEMS_SNAPSHOT CLOB NOT NULL
);
